# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 13:17
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_auto_20180918_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='meta',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
    ]
